// Code generated by go generate; DO NOT EDIT.

package api

import (
	"context"

	"albatross-2026-backend/config"
	"albatross-2026-backend/db"
)

var _ StrictServerInterface = (*HandlerWrapper)(nil)

type HandlerWrapper struct {
	impl Handler
}

func NewHandler(queries *db.Queries, hub GameHubInterface, conf *config.Config) *HandlerWrapper {
	return &HandlerWrapper{
		impl: Handler{
			q:    queries,
			hub:  hub,
			conf: conf,
		},
	}
}

func (h *HandlerWrapper) GetGame(ctx context.Context, request GetGameRequestObject) (GetGameResponseObject, error) {
	user, ok := GetJWTClaimsFromContext(ctx)
	if !ok {
		return GetGame401JSONResponse{
			Message: "Unauthorized",
		}, nil
	}
	return h.impl.GetGame(ctx, request, user)
}

func (h *HandlerWrapper) GetGamePlayLatestState(ctx context.Context, request GetGamePlayLatestStateRequestObject) (GetGamePlayLatestStateResponseObject, error) {
	user, ok := GetJWTClaimsFromContext(ctx)
	if !ok {
		return GetGamePlayLatestState401JSONResponse{
			Message: "Unauthorized",
		}, nil
	}
	return h.impl.GetGamePlayLatestState(ctx, request, user)
}

func (h *HandlerWrapper) GetGameWatchLatestStates(ctx context.Context, request GetGameWatchLatestStatesRequestObject) (GetGameWatchLatestStatesResponseObject, error) {
	user, ok := GetJWTClaimsFromContext(ctx)
	if !ok {
		return GetGameWatchLatestStates401JSONResponse{
			Message: "Unauthorized",
		}, nil
	}
	return h.impl.GetGameWatchLatestStates(ctx, request, user)
}

func (h *HandlerWrapper) GetGameWatchRanking(ctx context.Context, request GetGameWatchRankingRequestObject) (GetGameWatchRankingResponseObject, error) {
	user, ok := GetJWTClaimsFromContext(ctx)
	if !ok {
		return GetGameWatchRanking401JSONResponse{
			Message: "Unauthorized",
		}, nil
	}
	return h.impl.GetGameWatchRanking(ctx, request, user)
}

func (h *HandlerWrapper) GetGames(ctx context.Context, request GetGamesRequestObject) (GetGamesResponseObject, error) {
	user, ok := GetJWTClaimsFromContext(ctx)
	if !ok {
		return GetGames401JSONResponse{
			Message: "Unauthorized",
		}, nil
	}
	return h.impl.GetGames(ctx, request, user)
}

func (h *HandlerWrapper) GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error) {
	user, ok := GetJWTClaimsFromContext(ctx)
	if !ok {
		return GetMe401JSONResponse{
			Message: "Unauthorized",
		}, nil
	}
	return h.impl.GetMe(ctx, request, user)
}

func (h *HandlerWrapper) GetTournament(ctx context.Context, request GetTournamentRequestObject) (GetTournamentResponseObject, error) {
	user, ok := GetJWTClaimsFromContext(ctx)
	if !ok {
		return GetTournament401JSONResponse{
			Message: "Unauthorized",
		}, nil
	}
	return h.impl.GetTournament(ctx, request, user)
}

func (h *HandlerWrapper) PostGamePlayCode(ctx context.Context, request PostGamePlayCodeRequestObject) (PostGamePlayCodeResponseObject, error) {
	user, ok := GetJWTClaimsFromContext(ctx)
	if !ok {
		return PostGamePlayCode401JSONResponse{
			Message: "Unauthorized",
		}, nil
	}
	return h.impl.PostGamePlayCode(ctx, request, user)
}

func (h *HandlerWrapper) PostGamePlaySubmit(ctx context.Context, request PostGamePlaySubmitRequestObject) (PostGamePlaySubmitResponseObject, error) {
	user, ok := GetJWTClaimsFromContext(ctx)
	if !ok {
		return PostGamePlaySubmit401JSONResponse{
			Message: "Unauthorized",
		}, nil
	}
	return h.impl.PostGamePlaySubmit(ctx, request, user)
}

func (h *HandlerWrapper) PostLogin(ctx context.Context, request PostLoginRequestObject) (PostLoginResponseObject, error) {
	return h.impl.PostLogin(ctx, request)
}

func (h *HandlerWrapper) PostLogout(ctx context.Context, request PostLogoutRequestObject) (PostLogoutResponseObject, error) {
	user, ok := GetJWTClaimsFromContext(ctx)
	if !ok {
		return PostLogout401JSONResponse{
			Message: "Unauthorized",
		}, nil
	}
	return h.impl.PostLogout(ctx, request, user)
}
