openapi: 3.0.0
info:
  title: fortee API
  version: 0.1.0
tags: []
paths:
  /api/user/login:
    post:
      operationId: postLogin
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  loggedIn:
                    type: boolean
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                    required:
                      - username
                required:
                  - loggedIn
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
  /api/user/view/{username}:
    get:
      operationId: getUser
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  username:
                    type: string
                  avatar_url:
                    type: string
                required:
                  - uuid
                  - username
                  - avatar_url
        '404':
          description: The server cannot find the requested resource.
components: {}
