// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddMainPlayer(ctx context.Context, arg AddMainPlayerParams) error
	AggregateTestcaseResults(ctx context.Context, submissionID int32) (string, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (int32, error)
	CreateProblem(ctx context.Context, arg CreateProblemParams) (int32, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (int32, error)
	CreateTestcase(ctx context.Context, arg CreateTestcaseParams) (int32, error)
	CreateTestcaseResult(ctx context.Context, arg CreateTestcaseResultParams) error
	CreateTournament(ctx context.Context, arg CreateTournamentParams) (int32, error)
	CreateTournamentEntry(ctx context.Context, arg CreateTournamentEntryParams) error
	CreateTournamentMatch(ctx context.Context, arg CreateTournamentMatchParams) error
	CreateUser(ctx context.Context, username string) (int32, error)
	CreateUserAuth(ctx context.Context, arg CreateUserAuthParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, sessionID string) error
	DeleteTestcase(ctx context.Context, testcaseID int32) error
	DeleteTestcaseResultsBySubmissionID(ctx context.Context, submissionID int32) error
	DeleteTournamentEntries(ctx context.Context, tournamentID int32) error
	DeleteTournamentMatches(ctx context.Context, tournamentID int32) error
	GetGameByID(ctx context.Context, gameID int32) (GetGameByIDRow, error)
	GetLatestState(ctx context.Context, arg GetLatestStateParams) (GetLatestStateRow, error)
	GetLatestStatesOfMainPlayers(ctx context.Context, gameID int32) ([]GetLatestStatesOfMainPlayersRow, error)
	GetLatestSubmissionsByGameID(ctx context.Context, gameID int32) ([]Submission, error)
	GetProblemByID(ctx context.Context, problemID int32) (Problem, error)
	GetQualifyingRanking(ctx context.Context, arg GetQualifyingRankingParams) ([]GetQualifyingRankingRow, error)
	GetRanking(ctx context.Context, gameID int32) ([]GetRankingRow, error)
	GetSubmissionByID(ctx context.Context, submissionID int32) (Submission, error)
	GetSubmissionsByGameID(ctx context.Context, gameID int32) ([]Submission, error)
	GetTestcaseByID(ctx context.Context, testcaseID int32) (Testcase, error)
	GetTestcaseResultsBySubmissionID(ctx context.Context, submissionID int32) ([]TestcaseResult, error)
	GetTournamentByID(ctx context.Context, tournamentID int32) (Tournament, error)
	GetUserAuthByUsername(ctx context.Context, username string) (GetUserAuthByUsernameRow, error)
	GetUserByID(ctx context.Context, userID int32) (User, error)
	GetUserBySession(ctx context.Context, sessionID string) (User, error)
	GetUserIDByUsername(ctx context.Context, username string) (int32, error)
	ListAllGames(ctx context.Context) ([]Game, error)
	ListGameStateIDs(ctx context.Context) ([]ListGameStateIDsRow, error)
	ListMainPlayers(ctx context.Context, dollar_1 []int32) ([]ListMainPlayersRow, error)
	ListProblems(ctx context.Context) ([]Problem, error)
	ListPublicGames(ctx context.Context) ([]ListPublicGamesRow, error)
	ListSubmissionIDs(ctx context.Context) ([]int32, error)
	ListTestcases(ctx context.Context) ([]Testcase, error)
	ListTestcasesByGameID(ctx context.Context, gameID int32) ([]Testcase, error)
	ListTestcasesByProblemID(ctx context.Context, problemID int32) ([]Testcase, error)
	ListTournamentEntries(ctx context.Context, tournamentID int32) ([]ListTournamentEntriesRow, error)
	ListTournamentMatches(ctx context.Context, tournamentID int32) ([]TournamentMatch, error)
	ListTournaments(ctx context.Context) ([]Tournament, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveAllMainPlayers(ctx context.Context, gameID int32) error
	SyncGameStateBestScoreSubmission(ctx context.Context, arg SyncGameStateBestScoreSubmissionParams) error
	UpdateCode(ctx context.Context, arg UpdateCodeParams) error
	UpdateCodeAndStatus(ctx context.Context, arg UpdateCodeAndStatusParams) error
	UpdateGame(ctx context.Context, arg UpdateGameParams) error
	UpdateGameStartedAt(ctx context.Context, arg UpdateGameStartedAtParams) error
	UpdateGameStateStatus(ctx context.Context, arg UpdateGameStateStatusParams) error
	UpdateProblem(ctx context.Context, arg UpdateProblemParams) error
	UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) error
	UpdateTestcase(ctx context.Context, arg UpdateTestcaseParams) error
	UpdateTournament(ctx context.Context, arg UpdateTournamentParams) error
	UpdateTournamentMatchGame(ctx context.Context, arg UpdateTournamentMatchGameParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserIconPath(ctx context.Context, arg UpdateUserIconPathParams) error
}

var _ Querier = (*Queries)(nil)
